version: 2

project_name: terraflow

env:
  - COSIGN_YES=true

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/terraflow
    main: ./cmd/terraflow
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux
    goos: [linux]
    goarch: ["386", amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/terraflow
    main: ./cmd/terraflow
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: windows
    goos: [windows]
    goarch: ["386", amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: bin/terraflow
    main: ./cmd/terraflow
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: nix
    ids: [macos, linux]
    wrap_in_directory: false

  - id: windows
    ids: [windows]
    formats: zip

sboms:
  - id: default
    artifacts: source

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge pull request"
      - "^Merge branch"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - id: gpg
    cmd: gpg
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    artifacts: checksum
  - id: cosign
    signature: "${artifact}.sbom.json.bundle"
    cmd: cosign
    args:
      - sign-blob
      - --new-bundle-format
      - --bundle
      - "${signature}"
      - "${artifact}"
    artifacts: checksum

release:
  prerelease: auto
  github:
    owner: flowave-io
    name: terraflow

announce:
  discord:
    enabled: true
    message_template: |
      Terraflow {{ .Tag }} is now available!
      {{ .ReleaseURL }}
    author: 'terraflow'
    icon_url: ''
