name: Bug Report
description: Please inform us of any unexpected errors, or an incorrect behaviour.
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening an issue.

        Report any issues with Terraflow development experience.

        ## Creating a bug report

        To resolve issues effectively, we need clear, reproducible examples that can be run locally.
        Include only what's needed to trigger the bug. Remove extra variables, conditionals, modules, or resources that aren't relevant.

  - type: textarea
    id: tfl-version
    attributes:
      label: Terraflow Version
      description: Share your Terraflow version. If you're not on the latest version, consider upgrading first, your issue may have already been fixed.
      render: shell
      placeholder: Paste `terraflow version` output here...
      value:
    validations:
      required: true

  - type: textarea
    id: tf-version
    attributes:
      label: Terraform Version
      description: Share your Terraform version. If you're not on the latest version, consider upgrading first, your issue may have already been fixed.
      render: shell
      placeholder: Paste `terraform version` output here...
      value:
    validations:
      required: true

  - type: textarea
    id: tf-config
    attributes:
      label: Terraform Configuration Files
      description: Share the Terraform configuration that Terraflow is watching when the bug appears.
      placeholder:
      value: |
        ```terraform
        # Your Terraform configuration here
        ```
    validations:
      required: true

  - type: textarea
    id: tfl-expected
    attributes:
      label: Expected Behavior
      description: Describe what should have happened.
      placeholder: Describe the expected behavior...
      value:
    validations:
      required: true

  - type: textarea
    id: tfl-actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened. Include any error messages, unexpected console output.
      placeholder: Describe what actually happened...
      value:
    validations:
      required: true

  - type: textarea
    id: tfl-repro-steps
    attributes:
      label: Steps to Reproduce
      description: Provide a clear step-by-step guide on how to reproduce this bug. Include any console commands you ran, or interactions that led to the issue.
      placeholder: |
        1. `terraflow console`
        2. Make a change to your Terraform files
        3. Try evaluating an expression in the console
        4. See the bug occur
      value:
    validations:
      required: true

  - type: textarea
    id: tfl-add-context
    attributes:
      label: Additional Context
      description: Anything else we should know? This might include unusual command-line flags, environment variables, or specific Terraform/provider versions that seem relevant.
      placeholder: Any additional context that might help...
      value:
    validations:
      required: false

  - type: textarea
    id: tfl-references
    attributes:
      label: References
      description: |
        Link any related GitHub issues or Pull Requests:
        ```
          - #1234
        ```
      placeholder:
      value:
    validations:
      required: false
